#pragma once
#include "SysUtils.h"

#include <DirectXMath.h>
#include <d3d12.h>
#include <cstdint>
#include <memory>
#include <string_view>

struct ID3D12Device;
struct ID3D12GraphicsCommandList;
struct ID3D12Resource;

struct ffxDispatchDescDenoiserDirectDiffuse;
struct ffxDispatchDescDenoiserIndirectSpecular;
struct ffxDispatchDescDenoiser;

/**
 * @brief Converts DLSS Ray Reconstruction inputs into the format expected by FSR Ray Regeneration,
 * and handles composition for FSR-RR outputs.
 */
class FSRDPreprocessor_Dx12
{
  public:

    enum class ConvFlags : uint32_t
    {
        None = 0,

        IsDepthLinear =         1 << 1, // Interprets input depth as already linearized for view space calculations
        IsRoughnessPacked =     1 << 2, // Roughness = InNormals.A - NVSDK_NGX_DLSS_Roughness_Mode_Packed (Init param)
        RightHanded =           1 << 3, // View-space forward is negative Z
        HasSpecHitDistance =    1 << 4, // Indirect-specular A contains a valid ray hit distance
        SpecularSignalIndirect = 1 << 5, // Indirect A uses distance/-1; Direct A remains non-negative
        HasEmissiveInput =      1 << 6, // Optional GBuffer.Emissive input is bound
        FloorEnabled =     1 << 7, // Enable spatial floor and its detail reference
        MotionVectorsJittered = 1 << 8, // Source XY contains previous-current raster jitter
        DisplayResolutionMotion = 1 << 9, // Source MV texture uses display-resolution coordinates
        NormalsViewSpace =     1 << 11, // Transform input view-space normals to world space
        HasCombinedSpecHitDistance = 1 << 14, // Hit distance is combined resource alpha
        TitleLinearDepth =      1 << 12, // The title publishes its own linearised view depth
        HasResponsivityMask =   1 << 13, // The title publishes a per-pixel responsivity hint
        HasBiasMask =           1 << 15, // InBiasMask holds a real DLSS bias-current-color mask

        Debug =                 1 << 16, // Denoiser and upscaler bypassed for debug out if this is set
        DebugModeMask =         0xFF << 16,

        DebugOutRadiance =      Debug, // Default debug vis

        DebugInSpecHitDist =    1 << 17 | Debug,
        DebugInMotion =         2 << 17 | Debug,
        DebugInNormals =        3 << 17 | Debug,
        DebugInRoughness =      4 << 17 | Debug,
        DebugInDiffAlbedo =     5 << 17 | Debug,
        DebugInSpecAlbedo =     6 << 17 | Debug,

        DebugOutSignalSplit =   7 << 17 | Debug,
        DebugOutLinearDepth =   8 << 17 | Debug,
        DebugOutMotion =        9 << 17 | Debug,
        DebugOutNormals =       10 << 17 | Debug,
        DebugOutSpecAlbedo =    11 << 17 | Debug,
        DebugOutDiffAlbedo =    12 << 17 | Debug,

        DebugOutDepthDelta =    13 << 17 | Debug,
        DebugNormDepth =        14 << 17 | Debug,

        DebugAlbedoError =      15 << 17 | Debug,

        // 16 was the floor variance view; it went with the seed's unpublished instability channel.
        DebugFloorColor =       17 << 17 | Debug,

        // Remodulated RR signal before denoising. This is intentionally a
        // conversion debug mode so it displays the exact signal generated by
        // the DLSS-RR-to-FSR-RR packing pass.
        DebugRawIndirectSpecular = 18 << 17 | Debug,
        DebugEffectiveRoughness = 19 << 17 | Debug,
        DebugRawRoughness =      20 << 17 | Debug,
        DebugEmissiveMask =      21 << 17 | Debug,
        DebugAppliedRoughness = 22 << 17 | Debug,
        DebugResourceInspector = 23 << 17 | Debug,
        DebugMaterialType =      24 << 17 | Debug,
        DebugInEmissive =        25 << 17 | Debug,
        DebugRRMaterialType =    26 << 17 | Debug,
        DebugAlbedoStructure =   27 << 17 | Debug,
        DebugFloorResidual =    28 << 17 | Debug,

        // Optional-input validation views
        DebugSpecularSplit =     30 << 17 | Debug, // Specular signal's share of the demodulated split
        DebugInTitleLinearDepth = 31 << 17 | Debug,
        DebugTitleLinearDepthDiff = 32 << 17 | Debug,
        DebugInResponsivityMask = 33 << 17 | Debug,

        DebugFloorNoise =    38 << 17 | Debug, // Seed's robust local noise estimate
        DebugSkipUnmapped =      39 << 17 | Debug, // Skip share that modulation could not represent
        DebugSkipFloor =         40 << 17 | Debug, // Skip share contributed by the floor path
        DebugFloorExcess =     41 << 17 | Debug, // max(Floor - raw colour, 0)
        DebugInBiasMask =        34 << 17 | Debug, // Bias mask as applied, after strength scaling
        DebugDemodGain =         35 << 17 | Debug, // 1 / albedo used as the demodulation divisor
        DebugHitDistGate =       36 << 17 | Debug, // The specular tracking ramp on its own
        DebugDenoiserFraction =  37 << 17 | Debug, // Share of the pixel reaching the denoiser
        DebugDemodRisk =         42 << 17 | Debug, // Diagnostic: does the demod divisor implant structure
    };

    enum class CompFlags : uint32_t
    {
        None =                  0,
        RawSourceBlit =         1 << 0, // Bypass composition and write unmodified input
        ScaleSrc =              1 << 1, // Enable bilinear scaling to output
        DiffuseSignalIndirect = 1 << 2, // The active diffuse output was dispatched as Indirect Diffuse
        SpecularSignalIndirect = 1 << 3, // The active specular output was dispatched as Indirect Specular

        // Single-signal denoise mode. The disabled signal was not in the denoiser
        // chain this frame, so its ping-pong buffer still holds the floor pass's
        // intermediate result - remodulating that would tint the channel with the
        // floor image. Composition reads the packed raw signal instead, which is the
        // same demodulated radiance the denoiser would have consumed.
        DiffuseSignalDisabled = 1 << 4, // Diffuse was not denoised this frame
        SpecularSignalDisabled = 1 << 5, // Specular was not denoised this frame

        Debug =                 1 << 16,
        DebugModeMask =         0xFF << 16,

        DebugDetailConfidence =      1 << 17 | Debug,
        DebugSkipSignal =       2 << 17 | Debug,
        DebugDenoiserOutput =   3 << 17 | Debug,
        DebugDirectSpecular =   4 << 17 | Debug,
        DebugDirectDiffuse =    5 << 17 | Debug,
        DebugIndirectDiffuse =  6 << 17 | Debug,

        // Actual detail correction and the cleaned spatial reference.
        DebugDetailCorrection =     7 << 17 | Debug,
        DebugDetailReference = 8 << 17 | Debug,
        DebugIndirectSpecular =   12 << 17 | Debug,
        DebugReconstructedColor = 13 << 17 | Debug,
        DebugDetailSeed = 14 << 17 | Debug,
        DebugDetailAnchored = 15 << 17 | Debug,
        DebugHandoverWeights = 16 << 17 | Debug,
        DebugHandoverLimits = 17 << 17 | Debug,
        DebugCompositionBeforeClamp = 18 << 17 | Debug,
        DebugCompositionFinal = 19 << 17 | Debug,
        DebugDetailBoxAnchored = 20 << 17 | Debug,
        DebugHandoverEligibility = 21 << 17 | Debug,
        DebugChromaRecovery = 22 << 17 | Debug,
        DebugLumaRecovery = 23 << 17 | Debug,
    };

    /**
     * @brief Input resources matching DLSS Ray Reconstruction / NGX parameter names.
     * All resources must be in readable state before dispatch.
     */
    union InputResources
    {
        struct
        {
            ID3D12Resource* InColor; // RGB - NVSDK_NGX_Parameter_Color - HDR or SDR
            ID3D12Resource* InDepth; // R - NVSDK_NGX_Parameter_Depth - 24/32bits
            ID3D12Resource* InMotionVectors; // RG - NVSDK_NGX_Parameter_MotionVectors - RG16/RG32
            ID3D12Resource* InNormals; // RGB: Normals, A: Roughness (Optional) - NVSDK_NGX_Parameter_GBuffer_Normals - RGB16_FLOAT/RG32_FLOAT
            ID3D12Resource* InRoughness; // R - May be packed in normals. NVSDK_NGX_Parameter_GBuffer_Roughness
            ID3D12Resource* InSpecHitDist; // R - NVSDK_NGX_Parameter_DLSSD_SpecularHitDistance - FP16/FP32
            ID3D12Resource* InDiffAlbedo; // RGB - NVSDK_NGX_Parameter_GBuffer_DiffuseAlbedo - RGBA32
            ID3D12Resource* InSpecAlbedo; // RGB - NVSDK_NGX_Parameter_GBuffer_SpecularAlbedo - RGBA32
            ID3D12Resource* InBiasMask; // R8 - NVSDK_NGX_Parameter_DLSS_Input_Bias_Current_Color_Mask
            ID3D12Resource* InInspector; // Optional read-only RR resource-inspector input
            ID3D12Resource* InEmissive; // Optional NVSDK_NGX_Parameter_GBuffer_Emissive diagnostic input
            ID3D12Resource* InSpecularRayDirectionHitDistance; // Optional RGBA, distance in A
            // Optional diffuse ray length. RR's non-PSR reflection handling is driven
            // by hit distance, and the diffuse signal currently declares every pixel a
            // ray miss, so supplying a real length is the whole point of this input.
            ID3D12Resource* InDiffuseHitDistance;
            ID3D12Resource* InTitleLinearDepth; // Optional title-published linear view depth
            ID3D12Resource* InResponsivityMask; // Optional per-pixel responsivity hint
        };

    };

    /**
     * @brief Configuration and resources required for generating FSR-RR inputs from DLSS-RR
     * inputs.
     */
    struct ConversionDesc
    {
        InputResources Resources;

        DirectX::XMFLOAT4X4 InvViewMatrix;     // DLSSD WorldToView^1 - Camera matrix
        DirectX::XMFLOAT4X4 InvProjMatrix;     // DLSSD ViewToClip^-1 - Projection
        DirectX::XMFLOAT4X4 PrevViewMatrix;    // DLSSD WorldToView from last frame

        DirectX::XMFLOAT4 RenderSize;    // XY: Resolution of inputs - ZW: 1.0 / Resolution
        DirectX::XMFLOAT4 MotionInputSize; // XY: source MV extent - ZW: reciprocal extent
        DirectX::XMFLOAT4 MotionTransform; // XY: raw MV -> UV scale
        DirectX::XMFLOAT4 JitterOffsets; // XY: current pixels - ZW: previous pixels
        DirectX::XMUINT2 SpecularHitDistanceBase {};
        DirectX::XMUINT2 DiffuseHitDistanceBase {};
        // Origin of the title-published linear depth, when one is being consumed, and the
        // resource state it was validated in.
        DirectX::XMUINT2 TitleLinearDepthBase {};
        // The state the title declared for its linear depth, which the conversion records a
        // barrier out of and back into, and the state the denoiser's input is declared in.
        uint32_t TitleLinearDepthDeclaredState = 0;
        uint32_t TitleLinearDepthState = 0;

        // How to read InDiffuseHitDistance. 0 = absent, 1 = scalar in R,
        // 2 = combined ray-direction resource with the distance in A.
        uint32_t DiffuseHitDistanceMode = 0;

        // Packed uint2 source origins. Internal textures remain zero-based.
        DirectX::XMUINT4 FloorSourceBase; // XY: color, ZW: depth
        DirectX::XMUINT4 InputBase0; // XY: color, ZW: motion
        DirectX::XMUINT4 InputBase1; // XY: normals, ZW: roughness
        DirectX::XMUINT4 InputBase2; // XY: spec hit distance, ZW: diffuse albedo
        DirectX::XMUINT4 InputBase3; // XY: specular albedo, ZW: bias mask
        DirectX::XMUINT4 InputBase4; // XY: emissive, ZW: reserved

        float NearPlane; // Near < Far
        float FarPlane;  // Near < Far

        bool FloorEnabled = true;
        float FloorDetailPreservation = 0.35f;
        // The zero-rough domain's RR roughness is this pipeline's own compatibility value
        // (s_ZeroRoughRRRoughness), not a caller preference: there is no field for it.
        float DemodDivisorFloor = 8e-3f;

        // Turns this frame's probe readbacks on. Off unless asked for: the input probe copies
        // seven render targets into readback buffers and the output probe adds two more, which is
        // worth paying for while a number is being chased and worth nothing in a shipped build.
        bool DiagnosticsEnabled = false;

        uint32_t Flags; // Dynamic configuration flags. See: ConfigFlags
        uint32_t InspectorChannel;
        float InspectorScale;
        float DebugDepthMax = 1024.0f; // Full scale for the linear depth debug view

        // The responsivity hint is inert at zero. It reads the title's per-pixel statement about
        // where the denoiser's temporal history cannot be trusted, whose polarity
        // ResponsivityInvert selects.
        float ResponsivityTrustThreshold = 0.0f;
        bool ResponsivityInvert = false;

        float BiasMaskStrength = 1.0f;
        uint32_t RecoveryMask = 1;
        float SpecularAlbedoDemodulation = 1.0f;
        float DiffuseAlbedoModulation = 1.0f;
        float AdditiveLightSplit = 0.0f;
        bool MotionHistoryValid = false;
        bool MotionVectorsJittered = false;
        bool DisplayResolutionMotion = false;
        bool SpecularHitDistanceFromCombinedAlpha = false;

    };

    /**
     * @brief Configuration and external resources used for compositing denoiser output into final result.
     */
    struct CompositionDesc
    {
        DirectX::XMFLOAT4 DstTexSize; // XY = Tex Size - ZW = 1 / XY
        float FloorDetailPreservation = 0.35f;
        uint32_t Flags;
        uint32_t RecoveryMask = 1;
        float FloorHandoverAnchorClamp = 4.0f;
        float FloorHandoverCorrelationMix = 1.0f;
        float SpecularAlbedoDemodulation = 1.0f;
        float DiffuseAlbedoModulation = 1.0f;
        uint32_t SpatialTemporalMask = 0;
        float LumaRecovery = 1.0f;
        float ChromaRecovery = 1.0f;

    };

  public:

    FSRDPreprocessor_Dx12(std::string_view name, ID3D12Device* pDev);

    ~FSRDPreprocessor_Dx12();

    /**
     * @brief Indicates whether the converter has been successfully initialized.
     */
    bool IsInit() const;

    /**
     * @brief Returns the name of the shader instance
     */
    std::string_view GetName() const;

    /**
     * @brief (Re)allocates internal resources to match the specified render resolution.
     * Must be called at least once before any Dispatch().
     * @return True if resize succeeded
     */
    bool SetMaxRenderSize(uint32_t width, uint32_t height);

    /**
     * @brief Executes the input conversion shader.
     * Input resources must already be in shader-readable state.
     * RR input resources are left shader-readable and RR signal outputs are prepared for UAV writes.
     *
     * @param inputs Input resource pointers
     * @param constants Per-frame constant buffer values
     * @return True if dispatch completed successfully
     */
    bool DispatchConversion(ID3D12GraphicsCommandList* cmdList, const ConversionDesc& desc);

    /**
     * @brief Configures the RR 1.2 diffuse and specular signal resources.
     * The caller may retag the ABI-compatible descriptors as direct or indirect
     * before dispatch and must create the RR context with matching signal flags.
     * Signal inputs are shader-readable; signal outputs are in UAV state.
     * Resources remain valid until the next conversion or composition dispatch.
     * Must be re-acquired after each dispatch (lifetime managed internally).
     */
    void GetSignals(ffxDispatchDescDenoiser& dispatchDesc,
                    ffxDispatchDescDenoiserDirectDiffuse& directDiffuse,
                    ffxDispatchDescDenoiserIndirectSpecular& indirectSpecular) const;

    /**
     * @brief Composes the denoised radiance from FSR-RR with the skip signal previously generated 
     * by the converter, and writes the result to the given destination texture.
     */
    bool DispatchComposition(ID3D12GraphicsCommandList* cmdList, const CompositionDesc& desc);

    /**
     * @brief Returns denoiser output resources to shader-readable state.
     * Safe to call when the outputs are already readable. This closes the resource-state
     * lifetime after a bypassed or failed RR dispatch where composition did not run.
     */
    void TransitionDenoiserOutputsToRead(ID3D12GraphicsCommandList* cmdList) noexcept;

    // Commit helper history only after a successful normal frame, including upscale.
    void FinishCompositionHistory(bool successfulNormalFrame) noexcept;
    void InvalidateCompositionHistory() noexcept;

    void TransitionDenoiserOutputsToUav(ID3D12GraphicsCommandList* cmdList) noexcept;

    /**
     * @brief Returns a title-owned input the conversion transitioned to its state, so the
     * title finds the resource where it left it. Safe to call when nothing was transitioned.
     */
    void RestoreTitleInputStates(ID3D12GraphicsCommandList* cmdList) noexcept;

    /**
     * @brief Publishes the internally denoised AO signal to a tagged game resource and restores
     * both resources to their caller-visible states.
     */
    bool CopyAmbientOcclusionOutput(ID3D12GraphicsCommandList* cmdList, ID3D12Resource* dstTex,
                                    D3D12_RESOURCE_STATES dstState,
                                    uint32_t logicalWidth, uint32_t logicalHeight);

    ID3D12Resource* GetAmbientOcclusionOutput() const;
    ID3D12Resource* GetSpecularOcclusionOutput() const;

    /**
     * @brief Creates or reuses the dedicated RGBA16_FLOAT UAV used by AMD's internal RR debug views.
     * The returned resource is in unordered-access state and sized exactly as requested.
     */
    ID3D12Resource* PrepareDebugViewOutput(ID3D12GraphicsCommandList* cmdList, uint32_t width,
                                           uint32_t height);

    /**
     * @brief Transitions the AMD debug-view target to shader-readable state for presentation.
     */
    void TransitionDebugViewOutputToRead(ID3D12GraphicsCommandList* cmdList) noexcept;

    ID3D12Resource* GetDebugViewOutput() const;

    /**
     * @brief Returns the output from the last composition dispatch. Valid until the next conversion dispatch.
     */
    ID3D12Resource* GetCompositionOutput() const;

    /**
     * @brief Diagnostics: the denoiser's diffuse output texture and the
     * (demodulated) diffuse input signal it was dispatched with.
     */
    ID3D12Resource* GetDenoiserDiffuseOutput() const;
    ID3D12Resource* GetDenoiserDiffuseInputSignal() const;
    ID3D12Resource* GetDenoiserSpecularOutput() const;

    /**
     * @brief Diagnostics: the remaining RR dispatch g-buffer inputs, for the
     * input-quality probe (normals/roughness, motion vectors, linear depth).
     */
    ID3D12Resource* GetDenoiserNormalsInput() const;
    ID3D12Resource* GetDenoiserMotionInput() const;
    ID3D12Resource* GetDenoiserLinearDepthInput() const;

    /**
     * @brief Copies the contents of the given source texture. Does not automatically set resource barriers.
     */
    bool Blit(ID3D12GraphicsCommandList* cmdList, ID3D12Resource* srcTex, ID3D12Resource* dstTex,
              DirectX::XMFLOAT2 dstDim = {},
              DirectX::XMFLOAT2 logicalSrcDim = {},
              DirectX::XMFLOAT2 logicalSrcBase = {}) const;

    static bool RequestAdditiveCapture(uint32_t x, uint32_t y, uint32_t size);
    static std::string GetAdditiveCaptureStatus();

    // Pair the pending input journal with this same evaluation's composed pre-SR
    // output. Called only after successful normal RR and composition dispatches.
    void CompleteAdditiveCapture(ID3D12GraphicsCommandList* cmdList,
        const ffxDispatchDescDenoiser& dispatch, const CompositionDesc& composition,
        float preExposure, bool preExposureProvided) noexcept;

  private:
    struct Impl;

    std::unique_ptr<Impl> m_impl;
    std::string_view m_InstanceName;
    bool m_IsInitialized;
};
